"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import Link from "next/link"
import { useLocale, useTranslations } from "next-intl"
import { Check, Copy, ExternalLink, Plus, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { Switch } from "@/components/ui/switch"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { useSession } from "@/lib/auth/client"

interface Channel { id: string; channelType: "slack" | "teams"; label: string; enabled: boolean; createdAt: string }
interface Webhook { id: string; label: string; enabled: boolean; urlPreview: string | null; createdAt: string }
const MAX_PER_TYPE = 5; const MAX_WEBHOOKS = 10

export default function NotificationsSettingsPage() {
  const t = useTranslations("orgNotifications"); const locale = useLocale(); const { data: session } = useSession(); const requestRef = useRef(0); const copyRequestRef = useRef(0)
  const [role, setRole] = useState<string | null>(null); const [channels, setChannels] = useState<Channel[]>([]); const [webhooks, setWebhooks] = useState<Webhook[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [saving, setSaving] = useState(false)
  const [channelForm, setChannelForm] = useState<"slack" | "teams" | null>(null); const [channelLabel, setChannelLabel] = useState(""); const [channelUrl, setChannelUrl] = useState(""); const [webhookForm, setWebhookForm] = useState(false); const [webhookLabel, setWebhookLabel] = useState(""); const [webhookUrl, setWebhookUrl] = useState("")
  const [secret, setSecret] = useState<string | null>(null); const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState(false); const [deleteChannelId, setDeleteChannelId] = useState<string | null>(null); const [deleteWebhookId, setDeleteWebhookId] = useState<string | null>(null)
  const isAdmin = role === "admin" || role === "owner"
  const slackCount = useMemo(() => channels.filter((c) => c.channelType === "slack").length, [channels]); const teamsCount = useMemo(() => channels.filter((c) => c.channelType === "teams").length, [channels])
  const formatDate = (value: string) => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value))

  const load = useCallback(async () => {
    const request = ++requestRef.current; setLoading(true); setError(false)
    try {
      const [channelsRes, webhooksRes, membersRes] = await Promise.all([fetch("/api/org/notification-channels"), fetch("/api/org/webhooks"), fetch("/api/org/members")])
      if (!channelsRes.ok || !webhooksRes.ok || !membersRes.ok) throw new Error()
      const [channelData, webhookData, memberData] = await Promise.all([channelsRes.json(), webhooksRes.json(), membersRes.json()])
      if (request !== requestRef.current) return
      const members = memberData.members ?? memberData ?? []; const mine = members.find((m: { userId?: string; user?: { id?: string }; role?: string }) => m.userId === session?.user?.id || m.user?.id === session?.user?.id)
      setChannels(channelData.channels ?? []); setWebhooks(webhookData.webhooks ?? []); setRole(mine?.role ?? null)
    } catch { if (request === requestRef.current) setError(true) }
    finally { if (request === requestRef.current) setLoading(false) }
  }, [session?.user?.id])
  useEffect(() => { void load(); return () => { requestRef.current += 1 } }, [load])

  async function mutate(url: string, init: RequestInit, success: string) { try { const res = await fetch(url, init); if (!res.ok) throw new Error(); toast.success(t(success)); await load(); return true } catch { toast.error(t("actionError")); return false } }
  function openChannelForm(channelType: "slack" | "teams") { setChannelLabel(""); setChannelUrl(""); setChannelForm(channelType) }
  function closeChannelForm() { setChannelForm(null); setChannelLabel(""); setChannelUrl("") }
  function closeWebhookForm() { setWebhookForm(false); setWebhookLabel(""); setWebhookUrl("") }
  function closeSecret() { copyRequestRef.current += 1; setSecret(null); setCopyError(false); setCopied(false) }
  async function createChannel() { if (!channelForm || !channelLabel.trim() || !channelUrl.trim()) return; setSaving(true); const ok = await mutate("/api/org/notification-channels", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ channelType: channelForm, label: channelLabel, webhookUrl: channelUrl }) }, "channelAdded"); if (ok) closeChannelForm(); setSaving(false) }
  async function createWebhook(event: React.FormEvent) { event.preventDefault(); if (!webhookLabel.trim() || !webhookUrl.trim()) return; setSaving(true); try { const res = await fetch("/api/org/webhooks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label: webhookLabel, url: webhookUrl }) }); if (!res.ok) throw new Error(); const data = await res.json(); setSecret(data.signingSecret); closeWebhookForm(); await load() } catch { toast.error(t("actionError")) } finally { setSaving(false) } }
  async function copySecret() { if (!secret) return; const request = ++copyRequestRef.current; setCopyError(false); try { await navigator.clipboard.writeText(secret); if (request !== copyRequestRef.current) return; setCopied(true); window.setTimeout(() => { if (request === copyRequestRef.current) setCopied(false) }, 2000) } catch { if (request === copyRequestRef.current) setCopyError(true) } }

  const channelLimit = channelForm === "slack" ? slackCount >= MAX_PER_TYPE : teamsCount >= MAX_PER_TYPE
  return <div className="mx-auto w-full max-w-5xl space-y-8 p-4 sm:p-6 lg:p-8">
    <header className="space-y-1"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-primary">{t("eyebrow")}</p><h1 className="text-2xl font-semibold tracking-tight">{t("title")}</h1><p className="max-w-2xl text-sm text-muted-foreground">{t("subtitle")}</p></header>
    {error ? <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-5"><p className="font-medium">{t("loadError")}</p><p className="mt-1 text-sm text-muted-foreground">{t("loadErrorHelp")}</p><Button className="mt-4" variant="outline" onClick={() => void load()}>{t("retry")}</Button></div> : <>
      <section className="space-y-3" aria-labelledby="chat-heading"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="chat-heading" className="text-base font-semibold">{t("chatTitle")}</h2><p className="text-sm text-muted-foreground">{t("chatDescription")}</p></div><p className="text-xs text-muted-foreground">{t("chatCount", { slack: slackCount, teams: teamsCount, max: MAX_PER_TYPE })}</p></div>
        {loading ? <div className="grid gap-3 sm:grid-cols-2">{[0, 1].map((i) => <Skeleton key={i} className="h-28 w-full" />)}</div> : channels.length === 0 ? <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">{t("noChannels")}</div> : <div className="grid gap-3 sm:grid-cols-2">{channels.map((c) => <article key={c.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><Badge variant="outline">{t(`channelTypes.${c.channelType}`)}</Badge><h3 className="mt-2 font-medium">{c.label}</h3><p className="mt-1 text-xs text-muted-foreground">{t("created", { date: formatDate(c.createdAt) })}</p></div><Switch aria-label={t("enabledFor", { label: c.label })} checked={c.enabled} disabled={!isAdmin} onCheckedChange={isAdmin ? (enabled) => void mutate(`/api/org/notification-channels/${c.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled }) }, "channelUpdated") : undefined} /></div>{isAdmin && <Button aria-label={t("deleteChannel", { label: c.label })} className="mt-3" variant="ghost" size="sm" onClick={() => setDeleteChannelId(c.id)}><Trash2 className="h-4 w-4" />{t("delete")}</Button>}</article>)}</div>}
        {isAdmin && <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={slackCount >= MAX_PER_TYPE} onClick={() => openChannelForm("slack")}><Plus />{t("addSlack")}</Button><Button variant="outline" size="sm" disabled={teamsCount >= MAX_PER_TYPE} onClick={() => openChannelForm("teams")}><Plus />{t("addTeams")}</Button></div>}
        {isAdmin && channelForm && <form onSubmit={(e) => { e.preventDefault(); void createChannel() }} className="grid gap-4 rounded-xl border border-border bg-card p-4 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="channel-label">{t("channelLabel")}</Label><Input id="channel-label" value={channelLabel} onChange={(e) => setChannelLabel(e.target.value)} required /></div><div className="space-y-1.5"><Label htmlFor="channel-url">{t("channelUrl")}</Label><Input id="channel-url" type="password" autoComplete="new-password" value={channelUrl} onChange={(e) => setChannelUrl(e.target.value)} required /></div><div className="flex gap-2 sm:col-span-2"><Button size="sm" disabled={saving || channelLimit}>{saving ? t("saving") : t("add")}</Button><Button type="button" size="sm" variant="ghost" onClick={closeChannelForm}>{t("cancel")}</Button></div></form>}
      </section>
      <section className="space-y-3" aria-labelledby="webhooks-heading"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="webhooks-heading" className="text-base font-semibold">{t("webhooksTitle")}</h2><p className="text-sm text-muted-foreground">{t("webhooksDescription")}</p></div><p className="text-xs text-muted-foreground">{t("webhookCount", { count: webhooks.length, max: MAX_WEBHOOKS })}</p></div>
        {loading ? <div className="space-y-3"><Skeleton className="h-28 w-full" /><Skeleton className="h-28 w-full" /></div> : webhooks.length === 0 ? <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">{t("noWebhooks")}</div> : <div className="space-y-3">{webhooks.map((w) => <article key={w.id} className="rounded-xl border border-border bg-card p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="font-medium">{w.label}</h3><Badge variant={w.enabled ? "secondary" : "outline"}>{w.enabled ? t("enabled") : t("disabled")}</Badge></div><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{!w.urlPreview || w.urlPreview === "(unavailable)" ? t("previewUnavailable") : w.urlPreview}</p><p className="mt-1 text-xs text-muted-foreground">{t("created", { date: formatDate(w.createdAt) })}</p></div>{isAdmin && <div className="flex flex-wrap gap-2"><Button nativeButton={false} variant="outline" size="sm" render={<Link href={`/settings/notifications/webhooks/${w.id}/deliveries`} />}><ExternalLink />{t("viewDeliveries")}</Button><Button aria-label={t("deleteWebhook", { label: w.label })} variant="ghost" size="sm" onClick={() => setDeleteWebhookId(w.id)}><Trash2 />{t("delete")}</Button></div>}</div></article>)}</div>}
        {isAdmin && <Button aria-label={t("addWebhook")} variant="outline" size="sm" disabled={webhooks.length >= MAX_WEBHOOKS} onClick={() => setWebhookForm(true)}><Plus />{t("addWebhook")}</Button>}
        {isAdmin && webhookForm && <form onSubmit={createWebhook} className="grid gap-4 rounded-xl border border-border bg-card p-4 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="webhook-label">{t("webhookLabel")}</Label><Input id="webhook-label" value={webhookLabel} onChange={(e) => setWebhookLabel(e.target.value)} required /></div><div className="space-y-1.5"><Label htmlFor="webhook-url">{t("webhookUrl")}</Label><Input id="webhook-url" type="url" value={webhookUrl} onChange={(e) => setWebhookUrl(e.target.value)} required /></div><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={saving}>{saving ? t("creating") : t("create")}</Button><Button type="button" variant="ghost" onClick={closeWebhookForm}>{t("cancel")}</Button></div></form>}
      </section>
    </>}
    <Dialog open={!!deleteChannelId} onOpenChange={(open) => { if (!open) setDeleteChannelId(null) }}><DialogContent><DialogHeader><DialogTitle>{t("deleteChannelTitle")}</DialogTitle><DialogDescription>{t("deleteChannelDescription")}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteChannelId(null)}>{t("cancel")}</Button><Button variant="destructive" onClick={async () => { const id = deleteChannelId; setDeleteChannelId(null); if (id) await mutate(`/api/org/notification-channels/${id}`, { method: "DELETE" }, "channelDeleted") }}>{t("delete")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!deleteWebhookId} onOpenChange={(open) => { if (!open) setDeleteWebhookId(null) }}><DialogContent><DialogHeader><DialogTitle>{t("deleteWebhookTitle")}</DialogTitle><DialogDescription>{t("deleteWebhookDescription")}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteWebhookId(null)}>{t("cancel")}</Button><Button variant="destructive" onClick={async () => { const id = deleteWebhookId; setDeleteWebhookId(null); if (id) await mutate(`/api/org/webhooks/${id}`, { method: "DELETE" }, "webhookDeleted") }}>{t("delete")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!secret} onOpenChange={(open) => { if (!open) closeSecret() }}><DialogContent><DialogHeader><DialogTitle>{t("secretTitle")}</DialogTitle><DialogDescription>{t("secretDescription")}</DialogDescription></DialogHeader><div className="space-y-3"><Label htmlFor="signing-secret">{t("secretLabel")}</Label><div className="flex gap-2"><Input id="signing-secret" value={secret ?? ""} readOnly className="font-mono" onFocus={(e) => e.currentTarget.select()} /><Button aria-label={t("copySecret")} type="button" variant="outline" size="icon" onClick={() => void copySecret()}>{copied ? <Check /> : <Copy />}</Button></div>{copyError && <p role="alert" className="text-sm text-amber-700">{t("copyFailedManual")}</p>}<Button className="w-full" onClick={closeSecret}>{t("done")}</Button></div></DialogContent></Dialog>
  </div>
}
