import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import fs from "node:fs/promises"
import path from "node:path"
import { strToU8, unzipSync, zipSync } from "fflate"

const mocks = vi.hoisted(() => ({ execFile: vi.fn(), warn: vi.fn() }))
vi.mock("node:child_process", async (importOriginal) => {
  const actual = await importOriginal<typeof import("node:child_process")>()
  return { ...actual, default: { ...actual, execFile: mocks.execFile }, execFile: mocks.execFile }
})
vi.mock("@/lib/logger", () => ({ logger: { warn: mocks.warn } }))

import { pdfToDocxBuffer } from "@/lib/import/pdf-to-docx"

describe("PDF to editable document conversion", () => {
  const pdf = Buffer.from("%PDF-1.7 synthetic source")
  const docx = Buffer.from(zipSync({ "word/document.xml": strToU8("<document>Synthetic text</document>") }))
  let outputKind: "valid" | "malformed" | "oversized" | "symlink" | "error"
  let directory: string | undefined
  const reads: Array<ReturnType<typeof vi.spyOn>> = []

  beforeEach(() => {
    vi.resetAllMocks()
    outputKind = "valid"
    directory = undefined
    reads.length = 0
    const open = fs.open.bind(fs)
    vi.spyOn(fs, "open").mockImplementation(async (...args) => {
      const handle = await open(...args)
      reads.push(vi.spyOn(handle, "read"))
      return handle
    })
    mocks.execFile.mockImplementation((_binary, args: string[], _options, callback) => {
      directory = args[args.indexOf("--outdir") + 1]
      void (async () => {
        if (outputKind === "error") throw new Error("private contract content")
        const output = path.join(directory!, "source.docx")
        if (outputKind === "symlink") await fs.symlink(path.join(directory!, "source.pdf"), output)
        else {
          await fs.writeFile(output, outputKind === "malformed" ? "invalid generated archive" : docx)
          if (outputKind === "oversized") await fs.truncate(output, 50 * 1024 * 1024 + 1)
        }
      })().then(() => callback(null, "", ""), callback)
    })
  })

  afterEach(async () => {
    vi.restoreAllMocks()
    if (directory) await expect(fs.stat(directory)).rejects.toThrow()
  })

  it("uses fixed Writer import arguments, bounded execution and private temporary files", async () => {
    const result = await pdfToDocxBuffer(pdf)
    expect(result).not.toBeNull()
    expect(unzipSync(result!)).toEqual(unzipSync(docx))
    const [, args, options] = mocks.execFile.mock.calls[0]
    expect(args).toContain("--infilter=writer_pdf_import")
    expect(args[args.indexOf("--convert-to") + 1]).toBe("docx")
    expect(args.at(-1)).toBe(path.join(directory!, "source.pdf"))
    expect(args[0]).toMatch(/^-env:UserInstallation=file:/)
    expect(options).toEqual({ timeout: 30_000, killSignal: "SIGKILL", maxBuffer: 1024 * 1024 })
    expect(pdf.toString()).toBe("%PDF-1.7 synthetic source")
  })

  it("rejects oversized output before reading any generated bytes", async () => {
    outputKind = "oversized"
    expect(await pdfToDocxBuffer(pdf) === null).toBe(true)
    expect(reads.length).toBeGreaterThan(0)
    for (const read of reads) expect(read.mock.calls.length).toBe(0)
  })

  it.each(["malformed", "symlink", "error"] as const)("safely falls back on %s and cleans temporary files", async (kind) => {
    outputKind = kind
    expect(await pdfToDocxBuffer(pdf) === null).toBe(true)
    expect(mocks.warn).toHaveBeenCalledWith("[import] PDF conversion unavailable; falling back to text")
    expect(JSON.stringify(mocks.warn.mock.calls)).not.toContain("private contract content")
  })
})
