#!/bin/bash
# Aakd — One-command production deploy script
# Run this on a fresh Ubuntu 22.04 VM (Oracle Cloud ARM recommended)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/aaked-app/aakd/main/scripts/deploy.sh | bash
# Or after cloning the repo:
#   bash scripts/deploy.sh

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log()    { echo -e "${BLUE}[Aakd]${NC} $1"; }
success(){ echo -e "${GREEN}[✓]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
error()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

echo ""
echo -e "${BOLD}╔════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║        Aakd Production Deploy          ║${NC}"
echo -e "${BOLD}╚════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Check OS ───────────────────────────────────────────────────────────────
if [ "$(uname -s)" != "Linux" ]; then
  error "This script is for Linux only. Run it on your Oracle Cloud VM."
fi

# ── 2. Install Docker (if not installed) ─────────────────────────────────────
if ! command -v docker &> /dev/null; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  sudo usermod -aG docker "$USER"
  success "Docker installed"
else
  success "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
fi

# ── 3. Install Docker Compose plugin (if not installed) ──────────────────────
if ! docker compose version &> /dev/null; then
  log "Installing Docker Compose plugin..."
  sudo apt-get update -qq
  sudo apt-get install -y docker-compose-plugin
  success "Docker Compose installed"
else
  success "Docker Compose already installed ($(docker compose version --short))"
fi

# ── 4. Install git (if not installed) ────────────────────────────────────────
if ! command -v git &> /dev/null; then
  log "Installing git..."
  sudo apt-get update -qq && sudo apt-get install -y git
fi

# ── 5. Clone or update repo ───────────────────────────────────────────────────
REPO_DIR="${AAKD_REPO_DIR:-${CLAUSEFLOW_REPO_DIR:-${HOME}/aakd}}"
REPO_URL="${AAKD_REPO_URL:-${CLAUSEFLOW_REPO_URL:-https://github.com/aaked-app/aakd.git}}"

if [ -d "$REPO_DIR/.git" ]; then
  log "Pulling latest changes..."
  git -C "$REPO_DIR" pull origin main
  success "Repo updated"
else
  log "Cloning Aakd..."
  git clone "$REPO_URL" "$REPO_DIR"
  success "Repo cloned to $REPO_DIR"
fi

cd "$REPO_DIR"

# ── 6. Collect configuration ──────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Configuration${NC}"
echo "──────────────────────────────────────────"

if [ -f ".env.prod" ]; then
  warn ".env.prod already exists. Using existing configuration."
  warn "Delete .env.prod and re-run to reconfigure."
  source .env.prod 2>/dev/null || true
else
  # Domain. Set AAKD_DOMAIN for a non-interactive deploy.
  if [ -n "${AAKD_DOMAIN:-}" ]; then
    DOMAIN="$AAKD_DOMAIN"
  else
    read -rp "$(echo -e "${BOLD}Your domain name${NC} (e.g. clm.example.com): ")" DOMAIN
    DOMAIN="${DOMAIN:-clm.example.com}"
  fi
  if [[ ! "$DOMAIN" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
    error "DOMAIN must be a hostname such as clm.example.com"
  fi

  # Email is optional. Configure SMTP later if renewal and invitation emails are needed.
  RESEND_API_KEY="${RESEND_API_KEY:-}"
  if [ -z "$RESEND_API_KEY" ] && [ -t 0 ]; then
    read -rp "$(echo -e "${BOLD}Resend API key${NC} (optional, press Enter to skip): ")" RESEND_API_KEY
  fi
  if [ -t 0 ]; then
    read -rp "$(echo -e "${BOLD}From email address${NC} (optional, default noreply@${DOMAIN}): ")" SMTP_FROM
  fi
  SMTP_FROM="${SMTP_FROM:-noreply@${DOMAIN}}"

  if [ -z "${ALERT_EMAIL_TO:-}" ] && [ -t 0 ]; then
    read -rp "$(echo -e "${BOLD}Your email address${NC} (optional renewal alerts): ")" ALERT_EMAIL_TO
  fi
  ALERT_EMAIL_TO="${ALERT_EMAIL_TO:-}"

  # Auto-generate secrets
  log "Generating secrets..."
  POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 40)
  REDIS_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 40)
  MINIO_ROOT_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 40)
  BETTER_AUTH_SECRET=$(openssl rand -base64 32)
  NOTIFICATION_ENCRYPTION_KEY=$(openssl rand -hex 32)
  DOCUSEAL_SECRET_KEY_BASE=$(openssl rand -hex 64)

  # Write .env.prod
  cat > .env.prod << EOF
# Generated by deploy.sh on $(date)
DOMAIN=${DOMAIN}

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# Storage (MinIO)
MINIO_ROOT_USER=clauseflow
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# Auth
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}

# Notifications
NOTIFICATION_ENCRYPTION_KEY=${NOTIFICATION_ENCRYPTION_KEY}

# Email (Resend)
RESEND_API_KEY=${RESEND_API_KEY}
SMTP_FROM=${SMTP_FROM}
ALERT_EMAIL_TO=${ALERT_EMAIL_TO}

# DocuSeal
DOCUSEAL_SECRET_KEY_BASE=${DOCUSEAL_SECRET_KEY_BASE}
DOCUSEAL_API_KEY=
DOCUSEAL_WEBHOOK_SECRET=

# AI (optional — leave empty for BYOK)
AI_PROVIDER=
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-haiku-4-5
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini
OLLAMA_BASE_URL=
EOF
  chmod 600 .env.prod
  success ".env.prod created and locked (chmod 600)"
fi

# ── 7. Configure host firewall when explicitly requested ─────────────────────
if [ "${CONFIGURE_FIREWALL:-false}" = "true" ]; then
  log "Configuring host firewall (iptables)..."
if command -v iptables &> /dev/null; then
  # Oracle Cloud blocks all ports by default via iptables rules.
  # These rules allow HTTP and HTTPS traffic.
  sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT 2>/dev/null || true
  sudo iptables -I INPUT -p tcp --dport 443 -j ACCEPT 2>/dev/null || true
  sudo iptables -I INPUT -p udp --dport 443 -j ACCEPT 2>/dev/null || true
  # Persist rules across reboots
  if command -v netfilter-persistent &> /dev/null; then
    sudo netfilter-persistent save 2>/dev/null || true
  elif command -v iptables-save &> /dev/null; then
    iptables-save | sudo tee /etc/iptables/rules.v4 >/dev/null 2>&1 || true
  fi
  success "Firewall ports 80 and 443 opened"
else
  warn "iptables not found — make sure ports 80 and 443 are open in your VM's security list"
fi
else
  log "Skipping host firewall changes. Open ports 80 and 443 in your cloud firewall/security list."
fi

# ── 8. Build and start ───────────────────────────────────────────────────────
echo ""
log "Building Docker images (first build takes ~5 min)..."
docker compose -f docker-compose.prod.yml --env-file .env.prod config --quiet
docker compose -f docker-compose.prod.yml --env-file .env.prod build --parallel

log "Starting all services..."
docker compose -f docker-compose.prod.yml --env-file .env.prod up -d

# ── 9. Wait for app to be healthy ────────────────────────────────────────────
log "Waiting for app to be ready..."
ATTEMPTS=0
MAX_ATTEMPTS=30
until docker compose -f docker-compose.prod.yml --env-file .env.prod exec -T app wget -q --spider http://localhost:3000/api/health 2>/dev/null; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
    error "App health check timed out. Inspect: docker compose -f docker-compose.prod --env-file .env.prod logs app"
  fi
  sleep 5
done

# ── 10. Done ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║         Deploy Complete! 🚀             ║${NC}"
echo -e "${GREEN}${BOLD}╚════════════════════════════════════════╝${NC}"
echo ""

source .env.prod 2>/dev/null || true

echo -e "  ${BOLD}App:${NC}      https://${DOMAIN:-your-domain.com}"
echo -e "  ${BOLD}DocuSeal:${NC} https://sign.${DOMAIN:-your-domain.com}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Wait 1-2 min for Caddy to get SSL certificates"
echo "  2. Open https://${DOMAIN:-your-domain.com} and create your account"
echo "  3. Go to sign.${DOMAIN:-your-domain.com} → API → copy the key"
echo "     Then run: ./scripts/set-docuseal-key.sh YOUR_KEY"
echo ""
echo -e "${YELLOW}Useful commands:${NC}"
echo "  Logs:    docker compose -f docker-compose.prod.yml logs -f"
echo "  Status:  docker compose -f docker-compose.prod.yml ps"
echo "  Restart: docker compose -f docker-compose.prod.yml restart"
echo "  Update:  git pull && docker compose -f docker-compose.prod.yml up -d --build"
echo ""
